package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComSdedijerKotlinGitRefsHeadsNewTestBranch'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComSdedijerKotlinGitRefsHeadsNewTestBranch")
    name = "https://github.com/sdedijer/kotlin.git#refs/heads/new_test_branch"
    url = "https://github.com/sdedijer/kotlin.git"
    branch = "refs/heads/new_test_branch"
    authMethod = password {
        userName = "sdedijer"
        password = "credentialsJSON:d5f8e4d4-ab79-400f-b9bc-ad262dd5918e"
    }
}))

